# Generated by Django 6.0.5 on 2026-05-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
