# Generated by Django 6.0.5 on 2026-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trade', '0002_alter_trade_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='risk_percent',
            field=models.FloatField(default=1.0),
        ),
    ]
