# Generated by Django 6.0.5 on 2026-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trade', '0003_trade_risk_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='pair',
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default='EURUSD', max_length=10),
        ),
    ]
