# Generated by Django 6.0.5 on 2026-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trade', '0004_remove_trade_pair_trade_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
