# Generated by Django 6.0.5 on 2026-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trade', '0005_trade_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
